#!/bin/bash
./00-use-all-cores.sh
./10-display-manager.sh
./11-sound.sh
./12-bluetooth.sh
./13-printers.sh
./14-laptop-packages.sh
./20-software-arch-linux-repo.sh
./30-software-AUR-repo.sh
./40-fonts.sh
